### ISSUE TITLE
虽然我是白嫖，但是你在github上高收费很恶心

### ISSUE THREAD

**Issue by GongDianCheng** [wcwcug/pdf-password-remove#1]
下载软件要花钱开通的

**Comment by wcwcug** [comment]
回头买两瓶妇炎洁刷刷您沉鱼落雁的容貌好吗？
别以为你长的稀有样我们就应当物以稀为贵。
我也是网上找的资源。如果这个资源现在收费了，您可以选择不用？

**Comment by wcwcug** [comment]
你是有什么大病吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月31日(周日) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wcwcug/pdf-password-remove] 虽然我是白嫖，但是你在github上高收费很恶心 (Issue #1)




 
下载软件要花钱开通的
